create table products (
	product_id INT PRIMARY KEY,
	name VARCHAR(100),
	category VARCHAR(50),
	price DECIMAL(10,2),
	stock_quantity INT
);
insert into products (product_id, name, category, price, stock_quantity) values (653, 'White Rice', 'Food - Grains', 1.49, 785);
insert into products (product_id, name, category, price, stock_quantity) values (939, 'Outdoor Mosquito Repellent Lantern', 'Outdoor', 34.99, 737);
insert into products (product_id, name, category, price, stock_quantity) values (799, 'Cinnamon Roll Kit', 'Food - Baking', 6.89, 554);
insert into products (product_id, name, category, price, stock_quantity) values (881, 'Whole Grain Mustard', 'Food - Condiments', 3.49, 974);
insert into products (product_id, name, category, price, stock_quantity) values (349, 'Sweet Pea Hummus', 'Food - Dips', 4.29, 252);
insert into products (product_id, name, category, price, stock_quantity) values (278, 'Herbed Goat Cheese', 'Food - Cheese', 5.49, 321);
insert into products (product_id, name, category, price, stock_quantity) values (280, 'Beach Cover-Up', 'Clothing - Swimwear', 29.99, 782);
insert into products (product_id, name, category, price, stock_quantity) values (463, 'Shower Curtain Hooks', 'Home', 12.99, 852);
insert into products (product_id, name, category, price, stock_quantity) values (824, 'Pumpkin Puree', 'Food - Canned Goods', 2.99, 939);
insert into products (product_id, name, category, price, stock_quantity) values (644, 'Buffalo Cauliflower Bites', 'Food - Freezer', 6.29, 351);
insert into products (product_id, name, category, price, stock_quantity) values (749, 'Maple Bacon Potato Chips', 'Food - Snacks', 2.89, 576);
insert into products (product_id, name, category, price, stock_quantity) values (466, 'Reusable Snack Bags', 'Kitchen', 14.99, 194);
insert into products (product_id, name, category, price, stock_quantity) values (778, 'Pineapple Teriyaki Chicken Mix', 'Food - Meat', 6.99, 167);
insert into products (product_id, name, category, price, stock_quantity) values (738, 'Thai Red Curry Paste', 'Food - Condiments', 3.99, 905);
insert into products (product_id, name, category, price, stock_quantity) values (720, 'Pet Carrier', 'Pets', 39.99, 138);
insert into products (product_id, name, category, price, stock_quantity) values (120, 'High-Speed HDMI Cable', 'Electronics', 12.99, 567);
insert into products (product_id, name, category, price, stock_quantity) values (953, 'Memory Foam Pillow', 'Home', 39.99, 574);
insert into products (product_id, name, category, price, stock_quantity) values (689, 'Travel Beach Blanket', 'Outdoor', 29.99, 929);
insert into products (product_id, name, category, price, stock_quantity) values (226, 'Spaghetti Sauce', 'Food - Canned Goods', 2.99, 863);
insert into products (product_id, name, category, price, stock_quantity) values (42, 'Honeycrisp Apple Chips', 'Food - Snacks', 3.49, 598);
insert into products (product_id, name, category, price, stock_quantity) values (368, 'Organic Whole Wheat Flour', 'Food - Baking Goods', 2.99, 233);
insert into products (product_id, name, category, price, stock_quantity) values (30, 'Ramen Noodles', 'Food - Pasta', 0.99, 904);
insert into products (product_id, name, category, price, stock_quantity) values (175, 'Pet Carrier Backpack', 'Pets', 39.99, 129);
insert into products (product_id, name, category, price, stock_quantity) values (680, 'Ready-to-Eat Chili', 'Food - Soups', 2.99, 786);
insert into products (product_id, name, category, price, stock_quantity) values (855, 'Raisin Cinnamon Granola', 'Food - Cereals', 3.79, 585);
insert into products (product_id, name, category, price, stock_quantity) values (156, 'Maple Glazed Carrots', 'Food - Prepared Foods', 3.29, 206);
insert into products (product_id, name, category, price, stock_quantity) values (433, 'Graphic Tee', 'Clothing', 19.99, 18);
insert into products (product_id, name, category, price, stock_quantity) values (355, 'Gaming Headset', 'Gaming', 69.99, 60);
insert into products (product_id, name, category, price, stock_quantity) values (984, 'Fitness Resistance Bands Set', 'Fitness', 34.99, 158);
insert into products (product_id, name, category, price, stock_quantity) values (20, 'Chickpeas', 'Food - Canned Goods', 1.29, 995);
insert into products (product_id, name, category, price, stock_quantity) values (531, 'Mini Indoor Hydroponic Garden', 'Garden', 59.99, 247);
insert into products (product_id, name, category, price, stock_quantity) values (897, 'Tea Infuser', 'Kitchen', 12.99, 896);
insert into products (product_id, name, category, price, stock_quantity) values (462, 'Tea Set with Infuser', 'Kitchen', 34.99, 358);
insert into products (product_id, name, category, price, stock_quantity) values (767, 'Mushroom Soup (canned)', 'Food - Canned Goods', 2.49, 367);
insert into products (product_id, name, category, price, stock_quantity) values (336, 'Chocolate Peanut Butter Cups', 'Food - Snacks', 2.29, 542);
insert into products (product_id, name, category, price, stock_quantity) values (219, 'Electric Heat Press Machine', 'Crafts', 99.99, 600);
insert into products (product_id, name, category, price, stock_quantity) values (491, 'LED Desk Lamp', 'Home', 35, 629);
insert into products (product_id, name, category, price, stock_quantity) values (729, 'Skincare Set', 'Beauty', 54.99, 637);
insert into products (product_id, name, category, price, stock_quantity) values (252, 'Mesh Laundry Bags Set', 'Home', 12.99, 840);
insert into products (product_id, name, category, price, stock_quantity) values (809, 'Slim Wallet', 'Accessories', 24.99, 863);
insert into products (product_id, name, category, price, stock_quantity) values (586, 'Non-Stick Grill Pan', 'Kitchen', 39.99, 867);
insert into products (product_id, name, category, price, stock_quantity) values (889, 'Wireless Charger Stand', 'Electronics', 24.99, 423);
insert into products (product_id, name, category, price, stock_quantity) values (378, 'Infrared Space Heater', 'Home Appliances', 99.99, 965);
insert into products (product_id, name, category, price, stock_quantity) values (765, 'Digital Wireless Camera', 'Home Security', 199.99, 599);
insert into products (product_id, name, category, price, stock_quantity) values (95, 'Organic Fruit Salad', 'Food - Produce', 4.49, 784);
insert into products (product_id, name, category, price, stock_quantity) values (50, 'Brown Sugar', 'Food - Baking', 1.79, 739);
insert into products (product_id, name, category, price, stock_quantity) values (536, 'Skincare Fridge', 'Beauty', 39.99, 466);
insert into products (product_id, name, category, price, stock_quantity) values (85, 'Frozen Berry Medley', 'Food - Frozen Foods', 5.49, 387);
insert into products (product_id, name, category, price, stock_quantity) values (210, 'Personal Blender with Cups', 'Kitchen', 34.99, 447);
insert into products (product_id, name, category, price, stock_quantity) values (524, 'Thyme', 'Food - Fresh Produce', 2.49, 341);
insert into products (product_id, name, category, price, stock_quantity) values (677, 'Aeropress Coffee Maker', 'Kitchen', 29.99, 72);
insert into products (product_id, name, category, price, stock_quantity) values (776, 'Herb Seasoned Couscous', 'Food - Grains', 2.49, 903);
insert into products (product_id, name, category, price, stock_quantity) values (479, 'Raspberry Tart', 'Food - Baked Goods', 5.49, 57);
insert into products (product_id, name, category, price, stock_quantity) values (974, 'Kale Chips', 'Food - Snacks', 3.99, 680);
insert into products (product_id, name, category, price, stock_quantity) values (106, 'Brown Rice', 'Food - Grains', 1.79, 737);
insert into products (product_id, name, category, price, stock_quantity) values (946, 'Baby Monitor', 'Baby', 79.99, 264);
insert into products (product_id, name, category, price, stock_quantity) values (921, 'Ready-to-Eat Chili', 'Food - Soups', 2.99, 698);
insert into products (product_id, name, category, price, stock_quantity) values (580, 'Protein Powder', 'Fitness', 44.99, 432);
insert into products (product_id, name, category, price, stock_quantity) values (236, 'Shatterproof Wine Glasses', 'Outdoor', 24.99, 816);
insert into products (product_id, name, category, price, stock_quantity) values (366, 'Sun-Dried Tomato Pesto', 'Food - Condiments', 4.49, 985);
insert into products (product_id, name, category, price, stock_quantity) values (798, 'Garlic Parmesan Roasted Nuts', 'Food - Nuts', 4.89, 735);
insert into products (product_id, name, category, price, stock_quantity) values (543, 'Wire Shelving Unit', 'Home', 69.99, 948);
insert into products (product_id, name, category, price, stock_quantity) values (791, 'Lemon Herb Chicken', 'Food - Meat', 7.49, 982);
insert into products (product_id, name, category, price, stock_quantity) values (642, 'Feta Cheese', 'Food - Dairy', 4.99, 210);
insert into products (product_id, name, category, price, stock_quantity) values (706, 'Personal Blender', 'Kitchen', 39.99, 980);
insert into products (product_id, name, category, price, stock_quantity) values (255, 'Non-Stick Baking Sheets', 'Kitchen', 29.99, 240);
insert into products (product_id, name, category, price, stock_quantity) values (153, 'Mango Chia Pudding', 'Food - Snacks', 4.49, 422);
insert into products (product_id, name, category, price, stock_quantity) values (486, 'Mango Chutney', 'Food - Condiments', 3.99, 502);
insert into products (product_id, name, category, price, stock_quantity) values (778, 'Chicken Sausage', 'Food - Meat', 6.99, 704);
insert into products (product_id, name, category, price, stock_quantity) values (568, 'Pasta Maker Machine', 'Kitchen', 59.99, 26);
insert into products (product_id, name, category, price, stock_quantity) values (215, 'Banana Chips', 'Food - Snacks', 1.99, 749);
insert into products (product_id, name, category, price, stock_quantity) values (178, 'Fitness Tracker', 'Fitness', 49.99, 804);
insert into products (product_id, name, category, price, stock_quantity) values (915, 'Ergonomic Gaming Chair', 'Gaming', 199.99, 841);
insert into products (product_id, name, category, price, stock_quantity) values (186, 'Portable Charger with Solar Panel', 'Electronics', 45.99, 559);
insert into products (product_id, name, category, price, stock_quantity) values (67, 'Multi-Port USB Hub', 'Electronics', 19.99, 528);
insert into products (product_id, name, category, price, stock_quantity) values (269, 'Sunglasses', 'Accessories', 29.99, 834);
insert into products (product_id, name, category, price, stock_quantity) values (692, 'Adjustable Kneeling Pad', 'Garden', 18.99, 90);
insert into products (product_id, name, category, price, stock_quantity) values (896, 'Striped Long Sleeve Shirt', 'Clothing - Shirts', 29.99, 76);
insert into products (product_id, name, category, price, stock_quantity) values (863, 'Pet Leash', 'Pets', 15.99, 282);
insert into products (product_id, name, category, price, stock_quantity) values (318, 'Juice Extractor', 'Kitchen', 99.99, 401);
insert into products (product_id, name, category, price, stock_quantity) values (80, 'Heat-Resistant Silicone Mat', 'Kitchen', 19.99, 426);
insert into products (product_id, name, category, price, stock_quantity) values (386, 'Classic Slim Fit Shirt', 'Clothing - Shirts', 49.99, 363);
insert into products (product_id, name, category, price, stock_quantity) values (727, 'Recipe Book Stand', 'Kitchen', 22.99, 675);
insert into products (product_id, name, category, price, stock_quantity) values (293, 'Fettuccine Alfredo Dinner Kit', 'Food - Prepared Meals', 5.49, 384);
insert into products (product_id, name, category, price, stock_quantity) values (975, 'Body Wash', 'Beauty', 12.99, 754);
insert into products (product_id, name, category, price, stock_quantity) values (390, 'Sliced Bread', 'Food - Bakery', 2.99, 213);
insert into products (product_id, name, category, price, stock_quantity) values (267, 'Compact Pop-Up Tent', 'Outdoor', 69.99, 997);
insert into products (product_id, name, category, price, stock_quantity) values (929, 'Lentil Soup (canned)', 'Food - Canned Goods', 1.99, 933);
insert into products (product_id, name, category, price, stock_quantity) values (876, 'Backpack', 'Accessories', 49.99, 926);
insert into products (product_id, name, category, price, stock_quantity) values (611, 'Denim Jacket', 'Clothing - Outerwear', 69.99, 337);
insert into products (product_id, name, category, price, stock_quantity) values (733, 'Peanut Butter Banana Smoothie Mix', 'Food - Beverages', 4.49, 48);
insert into products (product_id, name, category, price, stock_quantity) values (255, 'Breezy Off-The-Shoulder Top', 'Clothing - Tops', 34.99, 14);
insert into products (product_id, name, category, price, stock_quantity) values (355, 'Wireless Range Extender', 'Electronics', 49.99, 907);
insert into products (product_id, name, category, price, stock_quantity) values (221, 'Manual Coffee Grinder', 'Kitchen', 22.99, 61);
insert into products (product_id, name, category, price, stock_quantity) values (285, 'Knitted Infinity Scarf', 'Clothing - Accessories', 29.99, 53);
insert into products (product_id, name, category, price, stock_quantity) values (898, 'Electric Wax Warmer', 'Home', 22.99, 815);
insert into products (product_id, name, category, price, stock_quantity) values (190, 'Multi-Function Smartphone Holder', 'Electronics', 12.99, 244);
insert into products (product_id, name, category, price, stock_quantity) values (278, 'Cranberry Orange Oatmeal', 'Food - Breakfast', 2.49, 286);
insert into products (product_id, name, category, price, stock_quantity) values (334, 'Spicy Thai Coconut Soup', 'Food - Soups', 3.99, 626);
insert into products (product_id, name, category, price, stock_quantity) values (643, 'Electric Knife', 'Kitchen', 39.99, 712);
