create table customers (
	customer_id INT PRIMARY KEY,
	name VARCHAR(100),
	email VARCHAR(100),
	gender VARCHAR(10),
	registration_date DATE,
	city VARCHAR(100),
	country VARCHAR(100)
);
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (616, 'Aimil Adamson', 'aadamson0@alibaba.com', 'Male', '2025-06-15 16:16:39', 'Hongping', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (77, 'Brear Parrott', 'bparrott1@plala.or.jp', 'Other', '2023-06-02 11:05:05', 'Cuihuangkou', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (218, 'Yevette Topham', 'ytopham2@spiegel.de', 'Female', '2024-06-03 22:52:23', 'Jagüey Grande', 'Cuba');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (491, 'Gertie Almack', 'galmack3@stumbleupon.com', 'Other', '2024-08-05 04:52:47', 'Karangtengah', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (874, 'Shepperd Mogridge', 'smogridge4@netvibes.com', 'Female', '2023-08-11 20:09:39', 'Xingang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (467, 'Nataniel Aylesbury', 'naylesbury5@narod.ru', 'Male', '2023-10-14 05:39:06', 'Wuquan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (51, 'Inglebert Matejovsky', 'imatejovsky6@cocolog-nifty.com', 'Other', '2025-05-18 09:23:57', 'Yanwo', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (631, 'Iggie Abbes', 'iabbes7@java.com', 'Male', '2023-09-09 02:36:41', 'Bazhu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (106, 'Raynard Marde', 'rmarde8@opera.com', 'Other', '2025-04-29 02:39:05', 'Vetlanda', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (127, 'Tommi Barthelemy', 'tbarthelemy9@hubpages.com', 'Female', '2023-08-17 13:30:54', 'Lianhe', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (27, 'Denny Birkenhead', 'dbirkenheada@opensource.org', 'Female', '2024-02-01 01:31:55', 'Kozakai-chō', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (287, 'Sasha Rainville', 'srainvilleb@tiny.cc', 'Male', '2023-04-06 22:33:36', 'Jingzhuang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (903, 'Tymothy Dewett', 'tdewettc@macromedia.com', 'Female', '2023-03-22 18:03:04', 'El Hamma', 'Tunisia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (49, 'Leila Alenichicov', 'lalenichicovd@smh.com.au', 'Male', '2024-10-10 10:16:58', 'La Libertad', 'Ecuador');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (477, 'Brena Haire', 'bhairee@eepurl.com', 'Male', '2024-03-31 13:48:44', 'Xiahong', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (208, 'Sephira Piggford', 'spiggfordf@chron.com', 'Female', '2024-10-28 13:14:19', 'Kuanfeu', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (535, 'Lexi Conan', 'lconang@constantcontact.com', 'Male', '2024-08-28 04:10:55', 'Shahrak', 'Afghanistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (296, 'Gustav Bertl', 'gbertlh@wufoo.com', 'Male', '2025-03-01 20:48:28', 'Fuyo', 'South Korea');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (334, 'Suzann Sabbin', 'ssabbini@globo.com', 'Other', '2024-02-02 11:15:41', 'Brades', 'Montserrat');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (458, 'Britney Simony', 'bsimonyj@google.pl', 'Other', '2024-03-16 03:01:47', 'Hokor', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (484, 'Fabiano Sherrett', 'fsherrettk@purevolume.com', 'Other', '2024-06-07 11:22:37', 'Dongtundu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (235, 'Gerri Doget', 'gdogetl@globo.com', 'Female', '2023-08-02 02:41:56', 'København', 'Denmark');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (380, 'North Buttrum', 'nbuttrumm@nyu.edu', 'Male', '2024-01-28 03:18:28', 'Beidajie', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (499, 'Oriana McQuaker', 'omcquakern@state.gov', 'Male', '2023-03-28 17:11:13', 'Paris 05', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (658, 'Morgana Devitt', 'mdevitto@fema.gov', 'Female', '2025-01-27 04:29:39', 'Bromölla', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (761, 'Federico719 Thurbon', 'fthurbonp@ovh.net', 'Male', '2023-10-16 19:23:40', 'Yirga ‘Alem', 'Ethiopia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (228, 'Brok Bosdet', 'bbosdetq@hhs.gov', 'Male', '2025-06-22 01:49:12', 'Palena', 'Chile');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (427, 'Othelia Kindley', 'okindleyr@photobucket.com', 'Other', '2023-04-07 00:21:11', 'Mhlambanyatsi', 'Swaziland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (662, 'Dulcie O''Crotty', 'docrottys@oaic.gov.au', 'Male', '2024-04-22 15:04:43', 'Kamloops', 'Canada');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (900, 'Jeanelle Velden', 'jveldent@bravesites.com', 'Female', '2024-02-17 13:39:59', 'Wattala', 'Sri Lanka');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (936, 'Emmanuel Stables', 'establesu@paginegialle.it', 'Male', '2023-02-22 16:23:15', 'Shaheying', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (840, 'Hally Sinden', 'hsindenv@vk.com', 'Female', '2025-07-04 19:13:21', 'Presidente Epitácio', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (337, 'Pauly Binder', 'pbinderw@elegantthemes.com', 'Other', '2024-01-17 21:20:09', 'Xianghu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (979, 'Marrissa Cleobury', 'mcleoburyx@cargocollective.com', 'Male', '2024-10-30 15:06:55', 'Santa Cruz del Sur', 'Cuba');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (662, 'Annmarie Conville', 'aconvilley@intel.com', 'Female', '2024-04-29 06:10:44', 'Sunfang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (708, 'Murial Garoghan', 'mgaroghanz@bloomberg.com', 'Other', '2023-09-18 11:15:24', 'Chaoyang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (317, 'Georgie Forri', 'gforri10@ibm.com', 'Female', '2024-05-04 19:24:37', 'Phichai', 'Thailand');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (395, 'Delia Espadater', 'despadater11@alibaba.com', 'Other', '2025-06-01 18:39:59', 'Beruniy', 'Uzbekistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (249, 'Ciel Crennan', 'ccrennan12@homestead.com', 'Other', '2025-05-08 07:50:56', 'Koszyce Wielkie', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (593, 'Bambi Giabuzzi', 'bgiabuzzi13@businessinsider.com', 'Female', '2024-12-23 00:32:24', 'Xiahan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (553, 'Cathi Rays', 'crays14@free.fr', 'Male', '2024-01-13 04:16:40', 'Yeshan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (691, 'Kayle Rockhall', 'krockhall15@is.gd', 'Female', '2025-01-13 10:11:37', 'Buikwe', 'Uganda');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (75, 'Neale Danilevich', 'ndanilevich16@msu.edu', 'Female', '2025-01-19 09:02:22', 'Yarmolyntsi', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (855, 'Rozella Guidotti', 'rguidotti17@zimbio.com', 'Male', '2023-08-05 05:15:05', 'Krajan', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (652, 'Der Hindsberg', 'dhindsberg18@dmoz.org', 'Female', '2024-10-23 18:48:20', 'Qila Abdullāh', 'Pakistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (47, 'Lukas Crombie', 'lcrombie19@alexa.com', 'Other', '2023-06-13 03:56:27', 'Arauca', 'Colombia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (338, 'Marven Reynard', 'mreynard1a@reference.com', 'Female', '2025-02-16 03:53:08', 'Newcastle', 'Saint Kitts and Nevis');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (377, 'Nevsa MacManus', 'nmacmanus1b@behance.net', 'Female', '2023-12-04 23:19:15', 'Järfälla', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (166, 'Bridgette Leeds', 'bleeds1c@ebay.com', 'Male', '2023-05-23 10:27:33', 'Ostankinskiy', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (95, 'Robinson Cree', 'rcree1d@live.com', 'Male', '2025-03-15 10:35:20', 'Sarrebourg', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (838, 'Gerard Tulloch', 'gtulloch1e@cafepress.com', 'Other', '2024-04-26 02:19:08', 'Canto', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (631, 'Reinaldos Cleaves', 'rcleaves1f@creativecommons.org', 'Other', '2024-03-24 21:51:26', 'Miki', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (258, 'Bendicty Wakeford', 'bwakeford1g@delicious.com', 'Male', '2024-07-31 11:56:44', 'Oranmore', 'Ireland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (423, 'Rochette McMarquis', 'rmcmarquis1h@webnode.com', 'Other', '2023-10-06 19:44:48', 'Starokucherganovka', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (776, 'Dorian Gwyneth', 'dgwyneth1i@squarespace.com', 'Other', '2024-03-10 04:06:16', 'Plagiári', 'Greece');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (479, 'Sabra McVicar', 'smcvicar1j@chicagotribune.com', 'Female', '2025-02-21 16:41:54', 'Takahagi', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (862, 'Vale McQuirk', 'vmcquirk1k@admin.ch', 'Male', '2024-07-31 22:35:08', 'Dingzhai', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (611, 'Milzie Morrowe', 'mmorrowe1l@tuttocitta.it', 'Male', '2024-01-31 17:45:18', 'Palaiochóri', 'Greece');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (329, 'Lyndsay Ovitz', 'lovitz1m@webnode.com', 'Male', '2024-02-07 21:44:25', 'Dao', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (1, 'Cedric Lunny', 'clunny1n@g.co', 'Female', '2024-07-11 14:21:35', 'Brétigny-sur-Orge', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (910, 'Layne Pecha', 'lpecha1o@wiley.com', 'Male', '2023-02-15 16:33:05', 'Damnica', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (743, 'Hagan McGrill', 'hmcgrill1p@over-blog.com', 'Male', '2023-06-24 00:40:16', 'Xinji', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (892, 'Vera Showte', 'vshowte1q@opensource.org', 'Male', '2024-07-16 04:06:15', 'Longquan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (903, 'Suzanne Fursey', 'sfursey1r@xrea.com', 'Female', '2024-06-03 15:38:36', 'Entre Rios', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (158, 'Guilbert O'' Markey', 'go1s@umich.edu', 'Female', '2025-05-23 18:23:02', 'Noisy-le-Grand', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (212, 'Sande Bril', 'sbril1t@weebly.com', 'Other', '2023-02-01 15:00:38', 'Mwembe', 'Tanzania');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (786, 'Nerty Nower', 'nnower1u@barnesandnoble.com', 'Female', '2023-05-05 23:41:25', 'San Jose', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (302, 'Mose McMichael', 'mmcmichael1v@slashdot.org', 'Female', '2024-04-13 06:59:36', 'Zliv', 'Czech Republic');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (551, 'Cami Bines', 'cbines1w@globo.com', 'Female', '2023-07-11 01:48:28', 'Gardinovci', 'Serbia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (340, 'Georges Stowell', 'gstowell1x@4shared.com', 'Other', '2025-02-02 11:01:27', 'Okunoya', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (104, 'Munmro Plewes', 'mplewes1y@github.io', 'Male', '2024-08-18 01:06:43', 'Gerdu', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (641, 'Ailbert Glenton', 'aglenton1z@digg.com', 'Female', '2023-03-14 10:21:22', 'Arras', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (50, 'Thea Trahmel', 'ttrahmel20@cpanel.net', 'Other', '2024-03-16 23:33:47', 'Oujda', 'Morocco');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (687, 'Kalina Calderon', 'kcalderon21@wikia.com', 'Female', '2023-01-31 12:15:19', 'Medina Estates', 'Ghana');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (983, 'Germain Marklund', 'gmarklund22@woothemes.com', 'Male', '2025-06-26 12:01:43', 'Pawitan', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (192, 'Granville Gaudin', 'ggaudin23@ehow.com', 'Male', '2023-03-10 11:54:58', 'Hongyansi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (141, 'Daphna808 Caddie', 'dcaddie24@senate.gov', 'Other', '2024-06-05 19:08:01', 'Slobidka', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (114, 'Allianora Trelevan', 'atrelevan25@discovery.com', 'Other', '2025-07-14 16:46:55', 'Alcala', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (721, 'Nate Garnson', 'ngarnson26@dyndns.org', 'Other', '2023-01-25 13:47:18', 'Machala', 'Ecuador');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (135, 'Emmalynne Sudran', 'esudran27@virginia.edu', 'Female', '2024-01-06 14:25:10', 'Timashëvsk', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (831, 'Roze Kendred', 'rkendred28@tinyurl.com', 'Male', '2024-06-10 00:17:58', 'Dalubian', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (327, 'Danna Bury', 'dbury29@bigcartel.com', 'Other', '2023-12-20 00:48:25', 'Jiakexi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (423, 'Travus Sudell', 'tsudell2a@ibm.com', 'Female', '2024-03-23 20:58:05', 'El Hermel', 'Lebanon');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (92, 'Duffie Yard', 'dyard2b@newsvine.com', 'Male', '2023-06-14 14:21:36', 'Komes', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (291, 'Rourke Thonason', 'rthonason2c@slideshare.net', 'Male', '2025-07-28 05:16:40', 'Lengji', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (601, 'Inness McGifford', 'imcgifford2d@nba.com', 'Female', '2023-07-10 05:20:24', 'Dubu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (894, 'Valery de Merida', 'vde2e@yellowpages.com', 'Other', '2023-08-30 06:03:34', 'Gaoqiao', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (474, 'Amil Metzing', 'ametzing2f@quantcast.com', 'Female', '2025-06-07 16:38:16', '5 de Mayo', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (336, 'Nissie Dmytryk', 'ndmytryk2g@hibu.com', 'Other', '2024-12-27 19:41:23', 'Strasbourg', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (621, 'Blancha Laird', 'blaird2h@hao123.com', 'Male', '2024-08-21 00:58:46', 'Forécariah', 'Guinea');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (507, 'Asher Dearn', 'adearn2i@google.de', 'Female', '2023-05-27 04:08:28', 'Pasarnangka', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (889, 'Elvira Athridge', 'eathridge2j@latimes.com', 'Female', '2025-04-28 02:46:07', 'Shujāābād', 'Pakistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (644, 'Bat Jude', 'bjude2k@wikispaces.com', 'Other', '2024-07-29 07:11:22', 'Monjarás', 'Honduras');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (219, 'Karna Hoggetts', 'khoggetts2l@msu.edu', 'Male', '2023-04-29 07:24:36', 'Qŭrghontepa', 'Uzbekistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (437, 'Lidia Dizlie', 'ldizlie2m@mysql.com', 'Female', '2024-11-25 12:00:41', 'Trondheim', 'Norway');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (741, 'Miranda Lob', 'mlob2n@smugmug.com', 'Female', '2023-03-14 18:20:26', 'Taltal', 'Chile');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (45, 'Asa Selliman', 'aselliman2o@mail.ru', 'Other', '2024-10-09 15:56:59', 'Litian', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (379, 'Caresa Novkovic', 'cnovkovic2p@sphinn.com', 'Male', '2023-08-08 11:50:10', 'Annan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (898, 'Leonid Bootherstone', 'lbootherstone2q@wp.com', 'Male', '2024-04-25 18:03:35', 'Krapivna', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (770, 'Alison Heathcott', 'aheathcott2r@twitpic.com', 'Other', '2025-04-23 13:34:40', 'Fujioka', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (282, 'Brendan Allsebrook', 'ballsebrook2s@ustream.tv', 'Female', '2025-03-25 10:05:07', 'Miłosław', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (986, 'Kimberly Jury', 'kjury2t@yolasite.com', 'Other', '2025-06-08 03:21:04', 'Dukuhsia', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (754, 'Barrie Eakeley', 'beakeley2u@sciencedirect.com', 'Male', '2024-09-19 23:48:56', 'El Jícaro', 'Guatemala');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (309, 'Timothea Surman-Wells', 'tsurmanwells2v@symantec.com', 'Male', '2024-10-20 15:42:02', 'Zili', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (851, 'Kaitlyn Bofield', 'kbofield2w@bing.com', 'Female', '2025-03-19 18:58:32', 'Osiedle-Nowiny', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (342, 'Chastity Muscott', 'cmuscott2x@sciencedirect.com', 'Male', '2024-03-19 19:19:47', 'Negreiros', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (47, 'Adelice Ings', 'aings2y@addthis.com', 'Other', '2024-05-02 02:36:26', 'Shuishiying', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (511, 'Jasen Wais', 'jwais2z@rakuten.co.jp', 'Male', '2024-07-08 20:43:47', 'Xuxiake', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (13, 'Ric Norley', 'rnorley30@berkeley.edu', 'Other', '2025-01-10 13:14:15', 'Sifangxi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (862, 'Pinchas Test', 'ptest31@cmu.edu', 'Male', '2023-10-15 00:32:01', 'Pilang', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (410, 'Artemus Coventry', 'acoventry32@oakley.com', 'Male', '2024-01-01 05:59:07', 'Salamá', 'Honduras');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (916, 'Josiah Cankett', 'jcankett33@nasa.gov', 'Male', '2024-02-28 02:16:22', 'Uspenskoye', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (252, 'Wynnie Steers', 'wsteers34@ihg.com', 'Male', '2023-09-18 20:52:56', 'Shifang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (354, 'Akim Kedslie', 'akedslie35@opensource.org', 'Male', '2023-04-20 17:44:54', 'Iowa City', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (450, 'Janessa Alexandersson', 'jalexandersson36@apache.org', 'Female', '2023-10-10 12:06:09', 'Canmore', 'Canada');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (56, 'Marvin Pitford', 'mpitford37@hexun.com', 'Male', '2025-03-27 14:05:24', 'Avignon', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (717, 'Lexie Eldershaw', 'leldershaw38@chron.com', 'Other', '2024-07-31 11:28:53', 'Fāqūs', 'Egypt');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (416, 'Merissa Riddiford', 'mriddiford39@1und1.de', 'Male', '2024-03-13 03:21:51', 'Olival Basto', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (671, 'Veronike Curedell', 'vcuredell3a@yolasite.com', 'Other', '2023-02-09 20:04:36', 'Boyarka', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (870, 'Cherianne Kersley', 'ckersley3b@themeforest.net', 'Other', '2023-04-20 19:08:13', 'Xinjian', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (883, 'Rosabella Streatley', 'rstreatley3c@linkedin.com', 'Other', '2023-09-08 06:39:45', 'Las Lajas', 'Honduras');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (98, 'Sukey Reisenstein', 'sreisenstein3d@a8.net', 'Female', '2023-05-24 14:06:15', 'Wenxian Chengguanzhen', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (1000, 'Faina Matthias', 'fmatthias3e@gravatar.com', 'Female', '2024-02-24 11:58:58', 'Fresnes', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (591, 'Ailene Brisse', 'abrisse3f@flickr.com', 'Other', '2024-07-09 11:26:24', 'Užice', 'Serbia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (719, 'Norrie Knotte', 'nknotte3g@bloglines.com', 'Male', '2023-02-21 11:18:55', 'Gwangju', 'South Korea');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (400, 'Timmie Dohr', 'tdohr3h@ft.com', 'Other', '2023-07-28 14:27:28', 'Santa Cruz de la Sierra', 'Bolivia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (938, 'Rip Fee', 'rfee3i@omniture.com', 'Female', '2024-09-16 03:40:08', 'Piggotts', 'Antigua and Barbuda');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (135, 'Derrik Laskey', 'dlaskey3j@google.ca', 'Other', '2024-11-05 11:27:59', 'Divo', 'Ivory Coast');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (953, 'Bridgette Briffett', 'bbriffett3k@oaic.gov.au', 'Female', '2023-07-31 11:42:08', 'Belgorod', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (827, 'Dido Scutter', 'dscutter3l@forbes.com', 'Other', '2024-07-24 20:18:49', 'Huanxi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (623, 'Warden Comford', 'wcomford3m@bravesites.com', 'Female', '2023-01-31 23:37:30', 'Bilshivtsi', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (167, 'Melinda640 Cantle', 'mcantle3n@nbcnews.com', 'Other', '2023-03-16 13:55:09', 'Rojas', 'Argentina');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (64, 'Hayes Betho', 'hbetho3o@cyberchimps.com', 'Other', '2023-02-15 22:50:57', 'Narita', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (277, 'Alvy Mersh', 'amersh3p@example.com', 'Other', '2025-02-09 12:05:32', 'Xinying', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (776, 'Tarrah Imison', 'timison3q@sun.com', 'Other', '2023-01-27 11:58:06', 'Maukaro', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (959, 'Zsazsa Chippindall', 'zchippindall3r@fema.gov', 'Female', '2023-09-04 00:31:04', 'Tanqiao', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (826, 'Cynde Besque', 'cbesque3s@vistaprint.com', 'Male', '2024-05-08 01:12:03', 'Kon Dơng', 'Vietnam');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (913, 'Celia Josifovitz', 'cjosifovitz3t@princeton.edu', 'Female', '2024-04-08 07:12:24', 'Dapawan', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (153, 'Renae Cicconetti', 'rcicconetti3u@redcross.org', 'Female', '2024-02-09 18:14:59', 'Hengshan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (8, 'Hobart McGillivray', 'hmcgillivray3v@ezinearticles.com', 'Male', '2023-05-25 08:53:52', 'Orzesze', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (20, 'Quintina Piatti', 'qpiatti3w@europa.eu', 'Male', '2025-06-22 13:48:11', 'Saumur', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (122, 'Pennie Wetheril', 'pwetheril3x@harvard.edu', 'Other', '2024-01-24 20:50:52', 'Rabat', 'Morocco');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (108, 'Sterling Bolus', 'sbolus3y@admin.ch', 'Female', '2025-02-12 22:45:53', 'Matanzas', 'Dominican Republic');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (623, 'Anabel Cluney', 'acluney3z@gizmodo.com', 'Male', '2025-02-15 17:02:47', 'Lianghe', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (139, 'Lindsey Fri', 'lfri40@google.co.uk', 'Female', '2024-03-23 02:52:07', 'Pengfang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (17, 'Chad Henfre', 'chenfre41@facebook.com', 'Male', '2025-05-02 04:11:21', 'Skaudvilė', 'Lithuania');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (475, 'Oralle Molder', 'omolder42@google.nl', 'Other', '2024-03-17 01:31:48', 'Marne-la-Vallée', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (278, 'Davie Helleckas', 'dhelleckas43@chicagotribune.com', 'Female', '2023-09-23 09:13:02', 'Ţayyibat al Imām', 'Syria');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (920, 'Mona Leadley', 'mleadley44@chron.com', 'Female', '2023-04-08 00:02:42', 'Stung Treng', 'Cambodia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (525, 'Van Beardshall', 'vbeardshall45@comcast.net', 'Female', '2023-08-05 00:30:13', 'Laiya', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (879, 'Marcelline McCormack', 'mmccormack46@rediff.com', 'Male', '2024-07-30 18:41:10', 'Fucheng', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (678, 'Krystalle Joll', 'kjoll47@unicef.org', 'Other', '2025-06-14 04:11:20', 'Massy', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (795, 'Bail Clara', 'bclara48@prnewswire.com', 'Female', '2023-08-21 23:54:30', 'Vischongo', 'Peru');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (470, 'Eudora Ivanchikov', 'eivanchikov49@trellian.com', 'Female', '2024-04-27 11:54:25', 'Nevinnomyssk', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (11, 'Gweneth Caswall', 'gcaswall4a@va.gov', 'Other', '2023-08-13 07:43:50', 'Sao Hai', 'Thailand');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (679, 'Georgi Monte', 'gmonte4b@nih.gov', 'Male', '2024-02-15 08:40:58', 'Soacha', 'Colombia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (976, 'Fabio606 Oppie', 'foppie4c@tamu.edu', 'Male', '2025-04-28 09:47:22', 'Olofström', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (963, 'Stacy Redihough', 'sredihough4d@vk.com', 'Male', '2023-05-19 10:17:20', 'Kertosari', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (618, 'Juan Simeoli', 'jsimeoli4e@icq.com', 'Female', '2023-04-12 16:03:54', 'Damai', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (473, 'Domenic Culp', 'dculp4f@mlb.com', 'Other', '2024-10-16 04:34:27', 'Tungor', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (388, 'Carmine Death', 'cdeath4g@behance.net', 'Female', '2024-02-09 17:01:44', 'Concepcion', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (627, 'Briny Andrysek', 'bandrysek4h@wiley.com', 'Female', '2023-10-07 16:54:24', 'Torsby', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (780, 'Cirstoforo Guille', 'cguille4i@google.pl', 'Male', '2024-11-06 21:31:57', 'Centenario', 'Argentina');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (514, 'Rodina Fortin', 'rfortin4j@skype.com', 'Other', '2023-03-12 23:09:24', 'Nova Iguaçu', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (503, 'Patricio Josefsohn', 'pjosefsohn4k@pbs.org', 'Male', '2023-01-30 07:59:13', 'Turrialba', 'Costa Rica');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (264, 'Lucien Gowenlock', 'lgowenlock4l@4shared.com', 'Female', '2023-12-18 00:41:50', 'Longquan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (495, 'Ingeberg Deport', 'ideport4m@furl.net', 'Other', '2023-02-19 19:05:54', 'Milovice', 'Czech Republic');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (116, 'Isadora Wederell', 'iwederell4n@jiathis.com', 'Other', '2025-05-16 23:13:15', 'Mont-Laurier', 'Canada');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (248, 'Flint Shatford', 'fshatford4o@biblegateway.com', 'Other', '2023-05-13 02:57:00', 'Vingåker', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (864, 'Idalia Livings', 'ilivings4p@ebay.co.uk', 'Male', '2025-02-21 09:03:58', 'Norashen', 'Armenia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (353, 'Olwen Elfes', 'oelfes4q@cnbc.com', 'Other', '2023-10-29 15:48:56', 'Cacoal', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (536, 'Octavius Draude', 'odraude4r@ibm.com', 'Male', '2024-03-04 10:53:16', 'Arnhem', 'Netherlands');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (54, 'Napoleon Jacquet', 'njacquet4s@uol.com.br', 'Other', '2023-08-24 12:58:54', 'Nizhneivkino', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (801, 'Jania Dodds', 'jdodds4t@posterous.com', 'Other', '2023-07-19 23:32:29', 'Austin', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (912, 'Adrea Larrosa', 'alarrosa4u@mozilla.org', 'Female', '2024-02-02 21:55:56', 'Praga Północ', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (656, 'Tyrus Rehm', 'trehm4v@constantcontact.com', 'Male', '2024-12-02 21:51:55', 'Tiaong', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (603, 'Paige Iannetti', 'piannetti4w@foxnews.com', 'Male', '2024-10-13 13:39:55', 'Mākū', 'Iran');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (514, 'Hakim Gooding', 'hgooding4x@army.mil', 'Other', '2023-10-09 02:10:04', 'Yolöten', 'Turkmenistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (133, 'Lilly Lipson', 'llipson4y@ibm.com', 'Female', '2023-12-22 11:13:24', 'Pateros', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (600, 'Sarajane Iacovides', 'siacovides4z@google.fr', 'Other', '2023-09-09 11:28:44', 'Baoshui', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (426, 'Moll Hannam', 'mhannam50@imageshack.us', 'Female', '2025-03-23 02:43:03', 'Powassan', 'Canada');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (463, 'Fletcher Gosson', 'fgosson51@europa.eu', 'Male', '2023-05-13 10:46:21', 'Jaboatão', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (936, 'Wright Test', 'wtest52@lulu.com', 'Male', '2024-02-25 07:50:05', 'Horní Čermná', 'Czech Republic');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (373, 'Madelle Knapman', 'mknapman53@barnesandnoble.com', 'Male', '2023-03-04 07:26:02', 'Murmuiža', 'Latvia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (677, 'Kelsy Oddboy', 'koddboy54@live.com', 'Female', '2023-01-16 00:45:39', 'Moravče', 'Slovenia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (417, 'Matthieu Berfoot', 'mberfoot55@histats.com', 'Male', '2023-07-06 13:36:14', 'Budziszewice', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (43, 'Greggory Thowless', 'gthowless56@naver.com', 'Male', '2024-08-29 17:53:33', 'Puerto Nariño', 'Colombia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (523, 'Keri Pering', 'kpering57@cisco.com', 'Other', '2023-05-17 01:11:52', 'Plaeng Yao', 'Thailand');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (289, 'Rozanna Ickovic', 'rickovic58@adobe.com', 'Other', '2024-07-13 05:23:47', 'Baucau', 'East Timor');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (832, 'Seamus Sargeaunt', 'ssargeaunt59@prlog.org', 'Male', '2025-06-28 17:13:03', 'Västervik', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (900, 'Marji Juanes', 'mjuanes5a@fotki.com', 'Other', '2023-11-27 16:54:17', 'Malasiqui', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (479, 'Karim Melliard', 'kmelliard5b@qq.com', 'Female', '2024-05-17 10:12:39', 'Malata', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (36, 'Sigismondo O''Hegertie', 'sohegertie5c@technorati.com', 'Male', '2024-10-12 16:22:20', 'Skibbereen', 'Ireland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (804, 'Laverna Samwyse', 'lsamwyse5d@is.gd', 'Female', '2023-08-24 14:56:45', 'Shimen', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (999, 'Wilie Ziems', 'wziems5e@dagondesign.com', 'Female', '2024-11-04 22:44:23', 'Babakanloa', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (331, 'Daloris Bidwell', 'dbidwell5f@histats.com', 'Male', '2025-04-29 00:47:48', 'Kitahiroshima', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (323, 'Arnoldo106 Goley', 'agoley5g@washington.edu', 'Female', '2023-03-04 23:01:14', 'Zengguang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (768, 'Elizabeth Dimmne', 'edimmne5h@nsw.gov.au', 'Other', '2025-02-14 09:29:06', 'Xietang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (440, 'Tomaso Spencer', 'tspencer5i@newsvine.com', 'Female', '2024-09-25 11:55:15', 'Chengtou', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (109, 'Stormi Lowle', 'slowle5j@amazonaws.com', 'Female', '2023-12-28 13:02:19', 'Tandahimba', 'Tanzania');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (95, 'Loretta Benazet', 'lbenazet5k@jiathis.com', 'Other', '2024-05-14 11:27:05', 'Milwaukee', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (442, 'Edgardo Charlin', 'echarlin5l@usa.gov', 'Male', '2024-10-18 13:45:52', 'Yeşilköy', 'Turkey');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (978, 'Marquita Loughton', 'mloughton5m@cpanel.net', 'Male', '2023-02-16 12:36:32', 'San Jose', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (751, 'Vinnie Banasik', 'vbanasik5n@cargocollective.com', 'Male', '2025-02-06 14:16:56', 'Bom Sucesso', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (567, 'Gaile Firk', 'gfirk5o@goo.gl', 'Male', '2024-12-14 22:46:32', 'Blagoveshchenka', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (470, 'Ruthie Allwood', 'rallwood5p@hhs.gov', 'Other', '2024-12-26 14:39:39', 'Turanj', 'Croatia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (600, 'Gusti Bonnar', 'gbonnar5q@blogspot.com', 'Male', '2023-04-24 01:33:52', 'Zhijiang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (87, 'Ag Conyers', 'aconyers5r@arstechnica.com', 'Female', '2025-01-06 06:34:12', 'Jojoima', 'Sierra Leone');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (71, 'Waylen Minton', 'wminton5s@hatena.ne.jp', 'Female', '2023-01-01 14:16:31', 'Andou', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (372, 'Sasha Thurley', 'sthurley5t@cnn.com', 'Other', '2025-02-24 22:23:55', 'Ngreco', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (728, 'Nils Getty', 'ngetty5u@dailymail.co.uk', 'Male', '2023-02-05 07:18:04', 'Baiba', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (703, 'Janey Boig', 'jboig5v@nydailynews.com', 'Other', '2023-01-23 00:26:00', 'Retenggoma', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (583, 'Verne Karczinski', 'vkarczinski5w@netscape.com', 'Other', '2023-06-26 13:01:44', 'Kanturk', 'Ireland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (913, 'Sauveur Purchon', 'spurchon5x@forbes.com', 'Other', '2023-03-06 04:52:08', 'La Cruz', 'Colombia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (904, 'Dagmar Sacher', 'dsacher5y@dell.com', 'Female', '2024-04-16 00:50:47', 'Xinó Neró', 'Greece');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (514, 'Sherwood Bamb', 'sbamb5z@de.vu', 'Male', '2023-01-29 04:04:18', 'Belopa', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (105, 'Ingunna Henken', 'ihenken60@arizona.edu', 'Male', '2023-07-01 00:13:31', 'Komyshuvakha', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (4, 'Nadeen Van Der Walt', 'nvan61@sfgate.com', 'Other', '2023-02-27 10:22:11', 'Jiangwan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (488, 'Lorry Springate', 'lspringate62@clickbank.net', 'Male', '2023-06-27 14:38:40', 'Xinji', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (385, 'Kathe Sanney', 'ksanney63@dedecms.com', 'Female', '2023-12-16 07:40:58', 'Buenavista', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (912, 'Alexio Pilsworth', 'apilsworth64@miibeian.gov.cn', 'Other', '2025-02-16 04:20:00', 'Cikaso', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (129, 'Elwood Silverton', 'esilverton65@tinyurl.com', 'Male', '2023-04-18 07:00:39', 'Lokatadho', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (338, 'Kailey Ghilks', 'kghilks66@slashdot.org', 'Female', '2024-12-19 10:19:13', 'Kampunglistrik', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (497, 'Dennis Chazerand', 'dchazerand67@angelfire.com', 'Other', '2023-05-12 10:00:45', 'Xibër-Murrizë', 'Albania');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (576, 'Lilllie Scamal', 'lscamal68@nymag.com', 'Male', '2023-02-14 23:31:07', 'Sobang', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (538, 'Tymothy Davenall', 'tdavenall69@gov.uk', 'Other', '2023-07-17 22:41:48', 'Longwan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (715, 'Janean Burges', 'jburges6a@blinklist.com', 'Female', '2025-04-17 12:39:32', 'Padre Burgos', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (758, 'Erastus Meneghelli', 'emeneghelli6b@addthis.com', 'Other', '2025-04-08 19:59:42', 'Naju', 'South Korea');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (44, 'Viviene Manicom', 'vmanicom6c@weebly.com', 'Other', '2024-03-23 22:05:10', 'Gongfang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (640, 'Cory Cranney', 'ccranney6d@123-reg.co.uk', 'Other', '2024-10-01 12:36:52', 'Omaha', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (796, 'Inna Kalaher', 'ikalaher6e@guardian.co.uk', 'Female', '2024-10-20 21:04:08', 'Barcelona', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (202, 'Darcy Cromb', 'dcromb6f@mayoclinic.com', 'Male', '2024-02-21 02:37:47', 'Xiangxiang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (915, 'Shane Scraggs', 'sscraggs6g@squidoo.com', 'Male', '2024-05-18 16:48:00', 'Lindavista', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (486, 'Angelita Goring', 'agoring6h@goo.gl', 'Other', '2025-04-03 22:05:45', 'La Esperanza', 'Colombia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (474, 'Agatha Vankov', 'avankov6i@biglobe.ne.jp', 'Other', '2024-07-23 15:00:29', 'Honoria', 'Peru');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (203, 'Babbie Masser', 'bmasser6j@google.com', 'Male', '2024-12-07 07:45:12', 'Kongkeshu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (109, 'Manfred Shackleton', 'mshackleton6k@imageshack.us', 'Female', '2023-09-19 03:46:50', 'Lizhai', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (488, 'Tannie Savine', 'tsavine6l@globo.com', 'Female', '2024-10-11 02:43:20', 'Keputran', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (895, 'Randolph Harcombe', 'rharcombe6m@over-blog.com', 'Male', '2024-12-18 10:29:59', 'Mamer', 'Luxembourg');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (506, 'Delores Chalker', 'dchalker6n@upenn.edu', 'Female', '2024-08-09 21:22:14', 'Paccha', 'Peru');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (875, 'Tawnya Loblie', 'tloblie6o@free.fr', 'Male', '2024-01-08 22:40:26', 'Guadalupe', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (790, 'Camel Taig', 'ctaig6p@washington.edu', 'Male', '2024-04-06 13:28:23', 'Vila', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (463, 'Damon Waddell', 'dwaddell6q@sbwire.com', 'Male', '2024-12-22 17:29:38', 'Rābigh', 'Saudi Arabia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (872, 'Tamas Hallward', 'thallward6r@sciencedirect.com', 'Female', '2025-05-13 22:59:07', 'Jīsh', 'Israel');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (394, 'Giavani Loble', 'globle6s@google.co.jp', 'Female', '2023-01-04 11:24:35', 'Arani', 'Bolivia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (361, 'Katharina Ouldcott', 'kouldcott6t@desdev.cn', 'Female', '2024-11-15 00:03:34', 'Ujung Gading', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (907, 'Carree Sambedge', 'csambedge6u@cmu.edu', 'Female', '2024-03-11 13:56:17', 'Banshu', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (599, 'Paige Morican', 'pmorican6v@is.gd', 'Male', '2024-09-03 22:04:15', 'Monastirákion', 'Greece');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (747, 'Raimondo Milton-White', 'rmiltonwhite6w@amazon.com', 'Female', '2023-02-02 12:04:09', 'Château-Richer', 'Canada');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (847, 'Abdel Ronca', 'aronca6x@jiathis.com', 'Male', '2023-11-18 04:44:22', 'Dayrūţ', 'Egypt');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (90, 'Magdaia Phillpot', 'mphillpot6y@ameblo.jp', 'Male', '2023-09-14 17:10:47', 'Alto de São Sebastião', 'Portugal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (225, 'Minta Kingsnorth', 'mkingsnorth6z@noaa.gov', 'Female', '2024-03-10 06:50:30', 'Walce', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (515, 'Elly Cowely', 'ecowely70@phpbb.com', 'Female', '2023-07-11 15:48:42', 'Áyioi Apóstoloi', 'Greece');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (97, 'Carey Bielfeld', 'cbielfeld71@senate.gov', 'Female', '2024-01-08 09:27:55', 'Tanjungpati', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (35, 'Jesse Cardozo', 'jcardozo72@eepurl.com', 'Female', '2023-07-11 09:19:10', 'Agudos', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (273, 'Esme Gyurko', 'egyurko73@discovery.com', 'Male', '2024-03-22 08:18:39', 'Panaoti', 'Nepal');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (92, 'Emlyn Weakley', 'eweakley74@businessinsider.com', 'Female', '2025-03-30 06:20:49', 'Niños Heroes', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (114, 'Constantia Freestone', 'cfreestone75@plala.or.jp', 'Male', '2024-04-17 18:52:42', 'Taozhuang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (976, 'Patrick Cutmere', 'pcutmere76@cnbc.com', 'Other', '2023-07-04 11:21:27', 'Beiqi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (872, 'Asa McNay', 'amcnay77@bloglines.com', 'Male', '2023-08-18 16:28:27', 'Boende', 'Democratic Republic of the Congo');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (102, 'Arda Godilington', 'agodilington78@mayoclinic.com', 'Other', '2024-10-03 11:07:53', 'Zhigulevsk', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (577, 'Jervis Hewell', 'jhewell79@epa.gov', 'Female', '2024-10-29 18:30:43', 'Lolotique', 'El Salvador');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (805, 'Sammy Mack', 'smack7a@wunderground.com', 'Male', '2024-07-20 06:47:50', 'Lyon', 'France');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (30, 'Courtnay Arundell', 'carundell7b@oracle.com', 'Other', '2024-01-06 19:54:38', 'Wulong', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (165, 'Inna Crowdson', 'icrowdson7c@salon.com', 'Male', '2023-07-29 20:16:40', 'Patzicía', 'Guatemala');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (503, 'Vinita Hutsby', 'vhutsby7d@gov.uk', 'Other', '2024-05-05 17:53:22', 'Berëzovyy', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (625, 'Vaughn324 Gumey', 'vgumey7e@webnode.com', 'Male', '2023-04-13 06:37:23', 'Vítkov', 'Czech Republic');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (985, 'Kent MacKaile', 'kmackaile7f@timesonline.co.uk', 'Male', '2023-09-06 00:20:36', 'Falun', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (30, 'Caro Harris', 'charris7g@nyu.edu', 'Male', '2025-05-13 11:58:55', 'Lins', 'Brazil');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (79, 'Roch Gouldie', 'rgouldie7h@storify.com', 'Female', '2023-05-06 04:25:23', 'Širvintos', 'Lithuania');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (744, 'Caterina Tunnacliffe', 'ctunnacliffe7i@printfriendly.com', 'Other', '2025-06-21 02:51:34', 'Lungaog', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (57, 'Pedro Duinkerk', 'pduinkerk7j@weather.com', 'Female', '2025-02-13 07:10:33', 'Siao', 'Thailand');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (691, 'Allyn Cottam', 'acottam7k@technorati.com', 'Other', '2025-06-13 07:58:12', 'Deje', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (672, 'Jeth Nipper', 'jnipper7l@dailymotion.com', 'Other', '2025-05-07 10:33:46', 'Jianggezhuang', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (864, 'Galvin Fairbairn', 'gfairbairn7m@eventbrite.com', 'Male', '2024-05-19 03:34:52', 'Ogawa', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (838, 'Lyn Whooley', 'lwhooley7n@creativecommons.org', 'Male', '2024-07-30 02:35:56', 'Krajan', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (508, 'Gus Charrett', 'gcharrett7o@mit.edu', 'Male', '2023-07-06 09:22:47', 'Chakwāl', 'Pakistan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (763, 'Dottie McDade', 'dmcdade7p@squidoo.com', 'Other', '2024-09-07 15:41:47', 'Merrifield', 'United States');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (983, 'Sydel Hillborne', 'shillborne7q@sohu.com', 'Female', '2024-04-16 23:59:41', 'Buenos Aires', 'Mexico');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (200, 'Cazzie Scadding', 'cscadding7r@sitemeter.com', 'Female', '2023-04-28 19:57:31', 'Noşratābād', 'Iran');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (339, 'Stafford Burnapp', 'sburnapp7s@nydailynews.com', 'Other', '2024-05-14 07:51:21', 'Senovo', 'Slovenia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (477, 'Boot Thirlwall', 'bthirlwall7t@wufoo.com', 'Female', '2025-03-11 19:57:37', 'Bururi', 'Burundi');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (973, 'Selinda Ropkins', 'sropkins7u@fema.gov', 'Female', '2023-04-23 00:40:20', 'Växjö', 'Sweden');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (1, 'Rutledge MacBey', 'rmacbey7v@bloomberg.com', 'Other', '2024-07-19 03:19:23', 'Mariposa', 'Peru');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (896, 'Arliene Heaney`', 'aheaney7w@naver.com', 'Male', '2024-03-01 06:39:39', '‘Anjarah', 'Jordan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (145, 'Maegan McAllister', 'mmcallister7x@ezinearticles.com', 'Female', '2024-01-14 21:55:45', 'Gelan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (424, 'Clayborn Chesshyre', 'cchesshyre7y@earthlink.net', 'Male', '2024-07-22 19:44:06', 'Bo Phloi', 'Thailand');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (748, 'Betsey Gallaher', 'bgallaher7z@free.fr', 'Other', '2024-11-23 03:26:02', 'Ishikari', 'Japan');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (620, 'Maxie Goadbie', 'mgoadbie80@uiuc.edu', 'Male', '2023-02-22 05:14:42', 'San José', 'Guatemala');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (798, 'Haywood Brandts', 'hbrandts81@shop-pro.jp', 'Male', '2024-10-11 12:26:10', 'Mautapaga Bawah', 'Indonesia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (573, 'Zia Soigne', 'zsoigne82@washington.edu', 'Male', '2024-05-31 04:40:15', 'Yanshan', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (389, 'Hildagard868 Langthorne', 'hlangthorne83@reference.com', 'Other', '2024-09-29 16:48:02', 'Shināş', 'Oman');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (663, 'Merrill Leyband', 'mleyband84@buzzfeed.com', 'Female', '2024-01-26 09:37:50', 'Novozavedennoye', 'Russia');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (81, 'Nessy Galero', 'ngalero85@spiegel.de', 'Female', '2024-02-03 22:09:27', 'Muricay', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (102, 'Irv Stronge', 'istronge86@washingtonpost.com', 'Male', '2023-06-20 00:47:48', 'Sadowie', 'Poland');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (871, 'Dolly Loble', 'dloble87@washingtonpost.com', 'Other', '2024-05-26 04:25:34', 'Ichnya', 'Ukraine');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (986, 'Margaux Keuning', 'mkeuning88@pen.io', 'Male', '2024-04-24 10:09:48', 'Hongshi', 'China');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (837, 'Gottfried Meachan', 'gmeachan89@huffingtonpost.com', 'Other', '2023-04-02 06:54:18', 'Bagong Pagasa', 'Philippines');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (994, 'Peyton Dalziel', 'pdalziel8a@usa.gov', 'Other', '2025-04-26 02:34:53', 'Chư Ty', 'Vietnam');
insert into customers (customer_id, name, email, gender, registration_date, city, country) values (96, 'Parry Sellek', 'psellek8b@princeton.edu', 'Female', '2023-11-02 16:53:59', 'Sigli', 'Indonesia');
